/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import slug from "custom-slug/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import vercelDeploy from "strapi-plugin-vercel-deploy/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor: ckeditor,
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    slug: slug,
    menus: menus,
    "multi-select": multiSelect,
    "vercel-deploy": vercelDeploy,
  },
});
